### ISSUE TITLE
Duplicate Ignore - Future of this package

### ISSUE THREAD

**Issue by harlan-zw** [windicss/vue-windicss-preprocess#6]
Hey @voorjaar 

Firstly, thanks for adding me to the org.

Was wondering if you'd be open to the idea of having someone take over the core development of this package?

The package is great and will likely be a dependency of a lot webpack-based Vue frameworks (Nuxt v2, vue-cli, etc). However for it to scale to these frameworks and reach further adoption, I feel like this package needs quite a bit of work.

In my mind that work would look like
- using a new js package that pulls out the duplicated logic from different implementations - have messaged @antfu about using his box implementation from the vite plugin
- get feature parity with the Vite plugin (where it's possible)
- add testing
- work on a v3 which would use a webpack plugin over a loader. It would be better suited to handle further features and optimisations and gives a better DX
 
For the last point, I think it would make sense to do one of the two (when the implementation is ready):

a. We create a new package called `vue-windicss-webpack-plugin` and we deprecate this one
b. We rename this package to `vue-windicss-webpack-plugin` 

`vue-windicss-preprocess` is a bit too ambiguous at the moment and doesn't limit the scope of what the package is trying to accomplish.

If all sounds good to you, would be great if I could get elevated permissions to this package and permission on npm to handle the release (username: harlan_zw).

Thanks either way and look forward to contributing where I can.

**Comment by antfu** [comment]
#7

**Comment by harlan-zw** [comment]
Think github was messing up, sorry for the duplicate
